### ISSUE TITLE
UnboundLocalError: local variable 'mismatch'

### ISSUE THREAD

**Issue by apolionl** [qtm-iisc/Twister#6]
Dear developers

I am trying to use the code and I am getting a error, while trying to run it. 

## 
Traceback (most recent call last):
  File "solid/Twister/SRC/get_angle.py", line 12, in <module>
    X=read_input("get_ang.inp")
  File "/solid/Twister/SRC/get_angle_funcs.py", line 959, in read_input
    return np.array(range_nm),np.array(celldm_a),np.array(a1),np.array(a2),np.array(a3),np.array(celldm_b),np.array(b1),np.array(b2),np.array(b3),np.array(theta_range),np.array(mismatch),np.array(fix_ang),np.array(f_ang),np.array(nba_a),np.array(nba_b),np.array(strain_per),np.array(plot),np.array(strain_layer),np.array(strain_tv),np.array(deepsearch),np.array(f_thresh)
UnboundLocalError: local variable 'mismatch' referenced before assignment
##

I have installed all the dependencies that are needed. The version in the CPC Library  has the same error. 

Thanks in advance

**Comment by apolionl** [comment]
OK  !!!

I kind of solve it  ... I had to manually overwrite the value of  mismatch. By this, I mean, I edited the file get_angle_funcs.py, adding: 

 mismatch=0.001

in the line 958. That way, it seems to be working. 
 Still, I consider that it should be solved in a more "pythonic" way.

**Comment by PSI-5** [comment]
Hello!

Sorry for the late reply. Could you send your input file (get_ang.inp) once? 

Thanks. 

> OK !!!
> 
> I kind of solve it ... I had to manually overwrite the value of mismatch. By this, I mean, I edited the file get_angle_funcs.py, adding:
> 
> mismatch=0.001
> 
> in the line 958. That way, it seems to be working. Still, I consider that it should be solved in a more "pythonic" way.

**Comment by apolionl** [comment]
OK.

I am posting the input here.

##
range_nm:
-30 29

celldm_a: 
3.1907 3.1907 14.2024

a1:
0.5 0.8660254 0.0

a2:
-0.5 0.8660254 0.0

a3:
0.0 0.0 1.0

Number_basis_atoms_a:
3

celldm_b:
3.3271 3.3271 15.0690

b1:
0.5 0.8660254 0.0

b2:
-0.5 0.8660254 0.0

b3:
0.0 0.0 1.0

Number_basis_atoms_b:
3

#Range of twist angle and step size
theta_range:
0.0 10.0 0.01

inital_mismatch_threshold (Angstrom):
0.1

final_mismatch_threshold (Angstrom):
0.00001

strain_tensor_vector:
'False'

strain_per:
0.5

strain_layer:
'Both'

fix_ang:
'True'

f_ang:
60

plot:
'T'

DeepSearch:
'True'

##


I think it is this one. Unfortunately, I am not 100% sure, cause since I fixed that error I have heavly modified this input .. kind of .

But, I tested with one on the test files provided with the scripts and I had the same problem. The one I testes was examples/Heterobilayer/Gr_hbn_0.0 

Thanks

**Comment by PSI-5** [comment]
> OK.
> 
> I am posting the input here.
> 
> range_nm: -30 29
> 
> celldm_a: 3.1907 3.1907 14.2024
> 
> a1: 0.5 0.8660254 0.0
> 
> a2: -0.5 0.8660254 0.0
> 
> a3: 0.0 0.0 1.0
> 
> Number_basis_atoms_a: 3
> 
> celldm_b: 3.3271 3.3271 15.0690
> 
> b1: 0.5 0.8660254 0.0
> 
> b2: -0.5 0.8660254 0.0
> 
> b3: 0.0 0.0 1.0
> 
> Number_basis_atoms_b: 3
> 
> #Range of twist angle and step size theta_range: 0.0 10.0 0.01
> 
> inital_mismatch_threshold (Angstrom): 0.1
> 
> final_mismatch_threshold (Angstrom): 0.00001
> 
> strain_tensor_vector: 'False'
> 
> strain_per: 0.5
> 
> strain_layer: 'Both'
> 
> fix_ang: 'True'
> 
> f_ang: 60
> 
> plot: 'T'
> 
> DeepSearch: 'True'
> 
> I think it is this one. Unfortunately, I am not 100% sure, cause since I fixed that error I have heavly modified this input .. kind of .
> 
> But, I tested with one on the test files provided with the scripts and I had the same problem. The one I testes was examples/Heterobilayer/Gr_hbn_0.0
> 
> Thanks

Hey, so the issue is the spelling of 'initial'. It has been misspelled as 'inital'. It has been corrected in Gr_hbn, thank you for pointing that out. 

Could you correct the spelling and try?

**Comment by apolionl** [comment]
Dear developer. 

Sorry for the delay. Now it is working like a charm. 

Thank you very much
